# 開発環境での動作確認用
version: "3"
services:
  db:
    image: satocheeen/279map-db:0.44.2
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: 279map-backend-odba-otakara:latest
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.otakara
    ports:
      - 8082:8082
    volumes:
        - ./log:/var/log/www
  frontend:
    # 任意のイメージを指定
    image: satocheeen/279map-frontend:0.44.6
    env_file:
      - ./.env
    ports: 
        - 3000:80
    volumes:
        - ./log:/var/log/www
  main:
    image: satocheeen/279map-backend-main:0.48.1
    depends_on:
      - db
    env_file:
      - ./.env
    ports: 
        - 443:443
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - ./etc:/usr/local/share
