# 開発環境での動作確認用
version: "3"
services:
  db:
    image: satocheeen/279map-db:0.45.6
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: satocheeen/279map-backend-odba-notion:0.45.0
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.notion
    ports:
      - 8082:8082
    volumes:
        - ./log:/var/log/www
  fs:
    # 任意のイメージを指定
    image: 279map-fs-local:latest
    env_file:
      - ./.env
    environment:
      HOST: http://localhost:8086
    volumes:
        - ./log:/var/log/www
        - ./fs:/var/www/279map/photo
  frontend:
    # 任意のイメージを指定
    image: 279map-frontend:latest
    env_file:
      - ./.env
    ports: 
        - 3000:80
    volumes:
        - ./log:/var/log/www
  main:
    image: satocheeen/279map-backend-main:0.50.0
    depends_on:
      - db
    env_file:
      - ./.env
    ports: 
        - 443:443
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - ./etc:/usr/local/share
        - 279map-dev-session-volume:/var/session
volumes:
  279map-dev-session-volume:
