# 開発環境での動作確認用
version: "3"
services:
  db:
    image: satocheeen/279map-db:0.57.0
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: satocheeen/279map-backend-odba-notion:0.75.1
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.notion
    ports:
      - 8082:8082
    volumes:
      - ./log:/var/log/www
      - ./photo:/var/photo
  frontend:
    # メイン
    image: satocheeen/279map-frontend:0.90.8
    env_file:
      - ./.env
    ports:
      - 3000:80
    volumes:
      - ./log:/var/log/www
  frontend-logregister:
    # スマホログ記録
    image: satocheeen/279map-frontend-logregister:0.3.0
  main:
    image: satocheeen/279map-backend-main:0.85.4
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - 279map-dev-session-volume:/var/session
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 444:444
    volumes:
      - ./log:/var/log/www
      - ./conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    tty: true
volumes:
  279map-dev-session-volume:
