# 開発環境での動作確認用
version: "3"
services:
  db:
    image: 279map-db:latest
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: 279map-backend-odba-notion:latest
    env_file:
      - ./.env
    ports:
      - 8082:8082
    volumes:
        - ./log:/var/log/www
  fs:
    # 任意のイメージを指定
    image: 279map-fs-local:latest
    env_file:
      - ./.env
    environment:
      HOST: http://localhost:8086
    volumes:
        - ./log:/var/log/www
        - ./fs:/var/www/279map/photo
  frontend:
    # 任意のイメージを指定
    image: 279map-frontend:latest
    env_file:
      - ./.env
    volumes:
        - ./log:/var/log/www
  main:
    image: 279map-backend-main:latest
    depends_on:
      - db
      - odba
    env_file:
      - ./.env
    ports: 
        - 443:443
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - ./etc:/usr/local/share
