# 開発環境での動作確認用
version: "3"
services:
  db:
    image: satocheeen/279map-db:0.58.0
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: satocheeen/279map-backend-odba-notion:0.80.7
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.notion
    ports:
      - 8082:8082
    volumes:
      - ./log:/var/log/www
  frontend:
    # メイン
    image: satocheeen/279map-frontend:0.99.0
    env_file:
      - ./.env
    ports:
      - 80:3000
    volumes:
      - ./log:/var/log/www
      - ./key:/var/key
  frontend-logregister:
    # スマホログ記録
    image: satocheeen/279map-frontend-logregister:0.3.0
  main:
    image: satocheeen/279map-backend-main:0.93.0
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
        - 81:81
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - 279map-dev-session-volume:/var/session
volumes:
  279map-dev-session-volume:
