# 開発環境での動作確認用
version: "3"
services:
  db:
    image: satocheeen/279map-db:0.48.0
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  odba:
    # 任意のイメージを指定
    image: satocheeen/279map-backend-odba-notion:0.50.0
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.notion
    ports:
      - 8082:8082
    volumes:
        - ./log:/var/log/www
        - ./photo:/var/photo
  frontend:
    # 任意のイメージを指定
    image: satocheeen/279map-frontend:0.52.0
    env_file:
      - ./.env
    ports: 
        - 3000:80
    volumes:
        - ./log:/var/log/www
  main:
    image: satocheeen/279map-backend-main:0.55.1
    depends_on:
      - db
    env_file:
      - ./.env
    ports: 
        - 80:80
        - 8083:8083
    volumes:
        - ./log:/var/log/www
        - 279map-dev-session-volume:/var/session
volumes:
  279map-dev-session-volume:
