mutation connect (
    $mapId: String!
) {
    connect(mapId: $mapId) {
        mapDefine {
            name
            useMaps
            defaultMapKind
            options {
                popupMode
                itemLabel
                guestUserAuthLevel
                newUserAuthLevel
                usePanels
                contentsSortCondition
                options
            }
            originalIcons
        }
        connect {
            sid
            authLv
            userId
            userName
        }
    }
}
mutation disconnect {
    disconnect
}

mutation switchMapKind (
    $mapKind: MapKind!
) {
    switchMapKind (
        mapKind: $mapKind
    ) {
        extent
        itemDataSources {
            datasourceId
            name
            groupName
            initialVisible
            config
        }
        contentDataSources {
            datasourceId
            name
            config
        }
    }
}

mutation registData (
    $datasourceId: String!
    $item: RegistDataItemInput
    $contents: ContentValueMap
    $linkItems: [DataId!]
) {
    registData (
        datasourceId: $datasourceId,
        item: $item,
        contents: $contents,
        linkItems: $linkItems,
    )
}

mutation removeData (
    $id: DataId!
) {
    removeData (
        id: $id
    )
}

mutation updateItems (
    $targets: [UpdateItemInput!]!
) {
    updateItems (
        targets: $targets
    ) {
        success
        error
    }
}

mutation updateContent (
    $id: DataId!
    $values: ContentValueMap!
) {
    updateContent(
        id: $id
        values: $values
    )
}

mutation linkContent (
    $id: DataId!
    $parent: ParentInput!
) {
    linkContent (
        id: $id
        parent: $parent
    )
}

mutation unlinkContent (
    $id: DataId!
    $parent: ParentInput!
) {
    unlinkContent (
        id: $id
        parent: $parent
    )
}

mutation changeAuthLevel (
    $userId: ID!
    $authLv: Auth!
) {
    changeAuthLevel(
        userId: $userId
        authLv: $authLv
    )
}

mutation request (
    $mapId: String!
    $name: String!
) {
    request(
        mapId: $mapId
        name: $name
    )
}
