mutation connect (
    $mapId: String!
) {
    connect(mapId: $mapId) {
        mapDefine {
            name
            useMaps
            defaultMapKind
            options {
                popupMode
                itemLabel
                guestUserAuthLevel
                newUserAuthLevel
                usePanels
                contentsSortCondition
                options
            }
            originalIcons
        }
        connect {
            sid
            authLv
            userId
            userName
        }
    }
}
mutation disconnect {
    disconnect
}

mutation switchMapKind (
    $mapKind: MapKind!
) {
    switchMapKind (
        mapKind: $mapKind
    ) {
        extent
        itemDataSources {
            datasourceId
            name
            groupName
            initialVisible
            config
        }
        contentDataSources {
            datasourceId
            name
            config
        }
    }
}

mutation registData (
    $datasourceId: String!
    $item: RegistDataItemInput
    $contents: ContentValueMap
    $linkItems: [DataId!]
) {
    registData (
        datasourceId: $datasourceId,
        item: $item,
        contents: $contents,
        linkItems: $linkItems,
    )
}

mutation updateData (
    $id: DataId!
    $item: RegistDataItemInput
    $deleteItem: Boolean
    $contents: ContentValueMap
) {
    updateData (
        id: $id,
        item: $item,
        deleteItem: $deleteItem,
        contents: $contents,
    )
}

mutation updateDataByOriginalId (
    $originalId: String!
    $item: RegistDataItemInput
    $contents: ContentValueMap
) {
    updateDataByOriginalId (
        originalId: $originalId,
        item: $item,
        contents: $contents,
    )
}

mutation removeData (
    $id: DataId!
) {
    removeData (
        id: $id
    )
}

mutation linkData (
    $id: DataId!
    $parent: DataId!
) {
    linkData (
        id: $id
        parent: $parent
    )
}

mutation linkDataByOriginalId (
    $originalId: String!
    $parent: DataId!
) {
    linkDataByOriginalId (
        originalId: $originalId
        parent: $parent
    )
}

mutation unlinkData (
    $id: DataId!
    $parent: DataId!
) {
    unlinkData (
        id: $id
        parent: $parent
    )
}

mutation changeAuthLevel (
    $userId: ID!
    $authLv: Auth!
) {
    changeAuthLevel(
        userId: $userId
        authLv: $authLv
    )
}

mutation request (
    $mapId: String!
    $name: String!
) {
    request(
        mapId: $mapId
        name: $name
    )
}
