mutation removeItem (
    $id: DataId!
) {
    removeItem(
        id: $id
    )
}

mutation registContent (
    $parent: ParentInput!
    $dataSourceId: String!

    $title: String!
    $overview: String
    $categories: [String!]
    $type: ContentType!
    $date: String
    $imageUrl: String
    $url: String
) {
    registContent(
        parent: $parent
        dataSourceId: $dataSourceId
        title: $title
        overview: $overview
        categories: $categories
        type: $type
        date: $date
        imageUrl: $imageUrl
        url: $url
    )
}

mutation updateContent (
    $id: DataId!
    $title: String
    $overview: String
    $categories: [String!]
    $type: ContentType!
    $date: String
    $imageUrl: String
    $url: String
) {
    updateContent(
        id: $id
        title: $title
        overview: $overview
        categories: $categories
        type: $type
        date: $date
        imageUrl: $imageUrl
        url: $url
    )
}

mutation linkContent (
    $id: DataId!
    $parent: ParentInput!
) {
    linkContent (
        id: $id
        parent: $parent
    )
}

mutation unlinkContent (
    $id: DataId!
    $parent: ParentInput!
) {
    unlinkContent (
        id: $id
        parent: $parent
    )
}

mutation removeContent (
    $id: DataId!
) {
    removeContent (
        id: $id
    )
}

mutation changeAuthLevel (
    $userId: ID!
    $authLv: Auth!
) {
    changeAuthLevel(
        userId: $userId
        authLv: $authLv
    )
}

mutation linkContentsDatasource (
    $contentsDatasources: [ContentsDatasourceInput!]!
) {
    linkContentsDatasource (
        contentsDatasources: $contentsDatasources,
    )
}
