query config {
    config {
        ...on NoneConfig {
            dummy
        }

        ...on Auth0Config {
            domain
            clientId
            audience
        }
    }
}
query getMapList {
    getMapList {
        mapId
        authLv
        name
        description
        thumbnail
    }
}
query getCategory(
    $datasourceIds: [String!]
){
    getCategory(datasourceIds: $datasourceIds) {
        name
        color
        datasourceIds
    }    
}

query getEvent(
    $datasourceIds: [String!]
){
    getEvent(datasourceIds: $datasourceIds) {
        itemDatasourceId
        contents {
            id
            date
        }
    }    
}

query getItems (
    $wkt: String!
    $zoom: Float!
    $datasourceId: String!
    $latestEditedTime: String
    $excludeItemIds: [String!]
) {
    getItems(wkt: $wkt, zoom: $zoom, datasourceId: $datasourceId, latestEditedTime: $latestEditedTime, excludeItemIds: $excludeItemIds) {
        id
        name
        geometry
        geoProperties
        lastEditedTime
        hasContents
        hasImageContentId
        contents {
            id
            children {
                id
            }
        }
    }
}

query getItemsById (
    $targets: [DataId!]!
) {
    getItemsById(targets: $targets) {
        id
        name
        geometry
        geoProperties
        lastEditedTime
        hasContents
        hasImageContentId
        contents {
            id
            children {
                id
            }
        }
    }
}
query getContent(
    $id: DataId!
) {
    getContent(id: $id) {
        ...content
    }
}

query getContents(
    $ids: [DataId!]!
) {
    getContents(ids: $ids) {
        ...content
    }
}

query getContentsInItem(
    $itemId: DataId!
) {
    getContentsInItem(itemId: $itemId) {
        ...content
        children {
            ...content
        }
    }
}

fragment content on ContentsDefine {
    id
    parentId
    values
    usingAnotherMap
    anotherMapItemId
    isSnsContent
    isEditable
    isDeletable
}

query getUnpointContents(
    $datasourceId: String!
    $nextToken: String
    $keyword: String
) {
    getUnpointContents(datasourceId: $datasourceId, nextToken: $nextToken, keyword: $keyword) {
        contents {
            id
            title
            thumb
            overview
        }
        nextToken
    }
}

query getThumb (
    $contentId: DataId!
) {
    getThumb(contentId: $contentId)
}

query getImage (
    $imageId: Int!
    $size: ThumbSize!
) {
    getImage(imageId: $imageId, size: $size)
}
query getImageUrl (
    $contentId: DataId!
) {
    getImageUrl(contentId: $contentId)
}

query search (
    $condition: Condition!
    $datasourceIds: [String!]
) {
    search(condition: $condition, datasourceIds: $datasourceIds) {
        id
        hitContents
        hitItem
    }
}

query geocoder (
    $address: String!
    $searchTarget: [GeocoderTarget!]!
) {
    geocoder(address: $address, searchTarget: $searchTarget) {
        idInfo
        name
        geometry
    }
}

query getGeocoderFeature (
    $id: GeocoderIdInfo!
) {
    getGeocoderFeature(id: $id)
}

query getSnsPreview (
    $url: String!
) {
    getSnsPreview(url: $url) {
        type
        posts {
            text
            media {
                type
                url
            }
            date
        }
    }
}
query getUserList {
    getUserList {
        id
        name
        authLv
    }
}

query getLinkableContentsDatasources {
    getLinkableContentsDatasources {
        datasourceId
        name
    }
}