query config {
    config {
        ...on NoneConfig {
            dummy
        }

        ...on Auth0Config {
            domain
            clientId
            audience
        }
    }
}
query getMapList {
    getMapList {
        mapId
        name
    }
}
query getCategory(
    $datasourceIds: [String!]
){
    getCategory(datasourceIds: $datasourceIds) {
        name
        color
        datasourceIds
    }    
}

query getEvent(
    $datasourceIds: [String!]
){
    getEvent(datasourceIds: $datasourceIds) {
        datasourceId
        dates
    }    
}

fragment geocoderIdInfo on GeocoderIdInfo {
    ... on GeocoderIdMapbox {
        id
    }
    ... on GeocoderIdOsm {
        osm_type
        osm_id
    }
}

query getItems (
    $wkt: String!
    $zoom: Float!
    $datasourceId: String!
    $latestEditedTime: String
    $excludeItemIds: [String!]
) {
    getItems(wkt: $wkt, zoom: $zoom, datasourceId: $datasourceId, latestEditedTime: $latestEditedTime, excludeItemIds: $excludeItemIds) {
        id {
            id
            dataSourceId
        }
        name
        geoJson
        geoProperties {
            ... on StructurePropeties {
                featureType
                icon {
                    type
                    id
                }
            }
            ... on RoadProperties {
                featureType
                lineJson
                width
            }
            ... on CircleProperties {
                featureType
                radius
            }
            ... on GeocoderFeatureProperties {                
                featureType
                geocoderIdInfo {
                    ...geocoderIdInfo
                }
            }
            ... on TrackPropeties {
                featureType
                minZoom
                maxZoom
            }
        }
        lastEditedTime
        hasContents
        hasImageContentId {
            id
            dataSourceId
        }
        temporary
    }
}

query getItemsById (
    $targets: [DataIdInput!]!
) {
    getItemsById(targets: $targets) {
        id {
            id
            dataSourceId
        }
        name
        geoJson
        geoProperties {
            ... on StructurePropeties {
                featureType
                icon {
                    type
                    id
                }
            }
            ... on RoadProperties {
                featureType
                lineJson
                width
            }
            ... on CircleProperties {
                featureType
                radius
            }
            ... on GeocoderFeatureProperties {
                featureType
                geocoderIdInfo {
                    ...geocoderIdInfo
                }
            }
            ... on TrackPropeties {
                featureType
                minZoom
                maxZoom
            }
        }
        lastEditedTime
        hasContents
        hasImageContentId {
            id
            dataSourceId
        }
        temporary
    }
}
query getContent(
    $id: DataIdInput!
) {
    getContent(id: $id) {
        ...content
    }
}

query getContents(
    $ids: [DataIdInput!]!
) {
    getContents(ids: $ids) {
        ...content
    }
}

query getContentsInItem(
    $itemId: DataIdInput!
) {
    getContentsInItem(itemId: $itemId) {
        ...content
        children {
            ...content
        }
    }
}

fragment content on ContentsDefine {
    id {
        id
        dataSourceId
    }
    itemId {
        id
        dataSourceId
    }
    date
    url
    title
    overview
    category
    image
    videoUrl
    parentId {
        id
        dataSourceId
    }
    usingAnotherMap
    anotherMapItemId {
        id
        dataSourceId
    }
    isSnsContent
    isEditable
    isDeletable
}

query getUnpointContents(
    $datasourceId: String!
    $nextToken: String
) {
    getUnpointContents(datasourceId: $datasourceId, nextToken: $nextToken) {
        contents {
            id {
                id
                dataSourceId
            }
            title
            thumb
            overview
        }
        nextToken
    }
}

query getThumb (
    $contentId: DataIdInput!
    $size: ThumbSize
) {
    getThumb(contentId: $contentId, size: $size)
}

query getImageUrl (
    $contentId: DataIdInput!
) {
    getImageUrl(contentId: $contentId)
}

query search (
    $condition: Condition!
    $datasourceIds: [String!]
) {
    search(condition: $condition, datasourceIds: $datasourceIds) {
        id {
            id
            dataSourceId
        }
        hitContents {
            id
            dataSourceId
        }
    }
}

query geocoder (
    $address: String!
    $searchTarget: [GeocoderTarget!]!
) {
    geocoder(address: $address, searchTarget: $searchTarget) {
        idInfo {
            ...geocoderIdInfo
        }
        name
        geoJson
    }
}

query getGeocoderFeature (
    $id: GeocoderIdInput!
) {
    getGeocoderFeature(id: $id)
}

query getSnsPreview (
    $url: String!
) {
    getSnsPreview(url: $url) {
        type
        posts {
            text
            media {
                type
                url
            }
            date
        }
    }
}
query getUserList {
    getUserList {
        id
        name
        authLv
    }
}

query getLinkableContentsDatasources {
    getLinkableContentsDatasources {
        datasourceId
        name
    }
}