# 地図上にアイテムが追加された場合に通知を受け取る
subscription dataInsertInTheMap (
    $mapId: String!
    $mapKind: MapKind!
) {
    dataInsertInTheMap(mapId: $mapId, mapKind: $mapKind) {
        id
        datasourceId
        hasItem
        hasContent
        wkt
    }
}

# 地図上のアイテムに更新があった場合に通知を受け取る
subscription dataUpdateInTheMap (
    $mapId: String!
    $mapKind: MapKind!
) {
    dataUpdateInTheMap(mapId: $mapId, mapKind: $mapKind) {
        id
        datasourceId
        hasItem
        hasContent
        wkt
    }
}

# 地図上のアイテムが削除された場合に通知を受け取る
subscription dataDeleteInTheMap (
    $mapId: String!
    $mapKind: MapKind!
) {
    dataDeleteInTheMap(mapId: $mapId, mapKind: $mapKind)
}

# 指定のデータが更新または削除された場合に通知を受け取る
subscription dataUpdate (
    $id: DataId!
) {
    dataUpdate(id: $id)
}

# 指定の地図のカテゴリに変更があった場合に通知を受け取る
subscription categoryUpdateInTheMap (
    $mapId: String!
    $mapKind: MapKind!
) {
    categoryUpdateInTheMap(mapId: $mapId, mapKind: $mapKind)
}

# ユーザ権限に更新があった場合に通知を受け取る
subscription updateUserAuth (
    $userId: ID!
    $mapId: String!
) {
    updateUserAuth(userId: $userId, mapId: $mapId)
}

# ユーザ一覧情報が更新された場合に通知を受け取る
subscription userListUpdate (
    $mapId: String!
) {
    userListUpdate(mapId: $mapId)
}

# 地図定義に変更があった場合に通知を受け取る
subscription mapInfoUpdate (
    $mapId: String!
) {
    mapInfoUpdate(mapId: $mapId)
}

subscription error (
    $sid: String!
) {
    error(sid: $sid) {
        type
        description
        itemId
    }
}