subscription test {
    test {
        message
    }
}
subscription test2 {
    test2(type: "AAA") {
        message
    }
}
subscription itemInsert(
    $mapId: String!
    $mapKind: MapKind!
) {
    itemInsert(mapId: $mapId, mapKind: $mapKind) {
        id
        wkt
    }
}