subscription test {
    test {
        message
    }
}

# 地図上のアイテムに追加があった場合に通知を受け取る
subscription itemInsert (
    $mapId: String!
    $mapKind: MapKind!
) {
    itemInsert(mapId: $mapId, mapKind: $mapKind) {
        id
        wkt
    }
}

# 地図上のアイテムに更新があった場合に通知を受け取る
subscription itemUpdate (
    $mapId: String!
    $mapKind: MapKind!
) {
    itemUpdate(mapId: $mapId, mapKind: $mapKind) {
        id
        wkt
    }
}
