enum ParentOfContent {
    Item
    Content
}
input ParentInput {
    type: ParentOfContent!
    id: DataId!
}
type Mutation {
    removeItem (
        id: DataId!
    ): Boolean

    updateContent (
        id: DataId!
        title: String
        overview: String
        categories: [String!]
        type: ContentType!
        date: String
        imageUrl: String
        url: String
    ): Boolean

    linkContent (
        id: DataId!
        parent: ParentInput!
    ): Boolean

    unlinkContent (
        id: DataId!
        parent: ParentInput!
    ): Boolean

    removeContent (
        id: DataId!
    ): Boolean

    changeAuthLevel (
        userId: ID!
        authLv: Auth!
    ): Boolean
}
