type Auth0Config {
    domain: String!
    clientId: String!
    audience: String!
}
type MapListItem {
    mapId: String!
    name: String!
    description: String
    thumbnail: String
    authLv: Auth!
}

"地図ページのメタ情報"
type MapMetaInfo {
    mapId: ID!
    title: String!
    description: String
    keyword: String
    image: String
}

"アイテムのメタ情報"
type ItemMetaInfo {
    id: DataId!
    "アイテムが属する地図種別"
    mapKind: MapKind!
    "アイテム名"
    name: String!
    "アイテムに紐づく画像"
    image: String
}

type NoneConfig {
    dummy: Boolean  # fragmentで種別判定するために型用意
}
union ServerConfig = Auth0Config | NoneConfig

type ItemDefine {
    id: DataId!
    datasourceId: String!
    name: String!
    geometry: Geometry!
    geoProperties: GeoProperties!
    lastEditedTime: String!

    "アイテムと対になるコンテンツ"
    content: ContentsDefine
}

type CategoryDefine {
    "対象のコンテンツデータソースID"
    datasourceId: String!
    "対象のフィールド"
    fieldKey: String!
    "属するカテゴリ一覧"
    categories: [CategoryItem!]!
}
type CategoryItem {
    value: String!
    color: String!
}
type EventDefine {
    itemDatasourceId: String!
    "日付を持つコンテンツ一覧"
    contents: [EventContent!]!
}
type EventContent {
    id: DataId!
    date: String!
}
enum ContentType {
    normal
    sns
}
type ContentsDefine {
    id: DataId!
    datasourceId: String!
    # コンテンツにタイトル以外の値が登録されている場合、true
    hasValue: Boolean!
    # 画像を持つ場合、true
    hasImage: Boolean!
    "紐づいているコンテンツのID一覧"
    linkedContents: [ContentsDefine!]!
}
type BackLink {
    "コンテンツが属するアイテムID"
    itemId: DataId!
    "アイテム名"
    itemName: String!
}
type ContentsDetail {
    id: DataId!
    datasourceId: String!
    "属性値"
    values: ContentValueMap!

    """
    もう片方の地図での、このコンテンツが属するアイテムID一覧
    （村マップ側では複数の建物に日本地図側の同一コンテンツが割り当たっている可能性もあるので、配列にしている）
    """
    backlinks: [BackLink!]!
    "他の地図でも参照されているか"
    usingOtherMap: Boolean!
    "trueの場合、ユーザ権限に関わらずreadonly"
    readonly: Boolean
}

"コンテンツが属するアイテム情報"
type BelongingItemInfo {
    "コンテンツが属するアイテムID"
    itemId: DataId!
    "アイテム名"
    name: String!
    "アイテムが属する地図種別"
    mapKind: MapKind!
    "アイテムからの距離"
    deep: Int!
}

type UnpointContent {
    originalId: String!
    "DBに登録済みの場合は、dataIdも返す"
    dataId: DataId
    title: String!
    overview: String
    hasImage: Boolean
}
type AllocatableContentsResult {
    contents: [UnpointContent!]!
    nextToken: String
}
# getThumbで返す画像サイズ
enum ThumbSize {
    Thumbnail
    Medium
}
type ContentsDatasource {
    datasourceId: String!
    name: String!
}

# --------------
# search関連
# --------------
input Condition {
    category: [CategoryCondition!]
    date: [DateCondition!]
    keyword: [String!]
}
input CategoryCondition {
    "対象のコンテンツデータソースID"
    datasourceId: String!
    "対象のフィールド"
    fieldKey: String!
    "カテゴリ値"
    value: String!
}
input DateCondition {
    "日付文字列"
    date: String!
    "クライアント端末のUTCからの時差"
    utcOffset: Int!
}

# --------------
# geocoder関連
# --------------
enum GeocoderTarget {
    Point
    Area
}

type GeocoderItem {
    idInfo: GeocoderIdInfo!
    name: String!
    geometry: Geometry!
}

# --------------

type Query {
    config: ServerConfig!

    "ユーザがアクセス可能な地図情報一覧を返す"
    getMapList: [MapListItem!]!

    "地図のメタ情報を返す。ユーザがアクセス不可能な地図については、エラー"
    getMapMetaInfo (
        mapId: ID!
    ): MapMetaInfo!

    "指定の地図の指定のアイテムのメタ情報を返す。ユーザがアクセス不可能な地図については、エラー"
    getItemMetaInfo (
        mapId: ID!
        itemId: DataId!
    ): ItemMetaInfo!

    getItems(
        wkt: String!,
        zoom: Float!,
        datasourceId: String!,

        "(optional) 指定されている場合、この更新日時以降に更新されたアイテムのみ返す"
        latestEditedTime: String

        "(optional) 指定されている場合、このidのアイテムは結果から除く TODO: deprecated"
        excludeItemIds: [DataId!]
    ): [ItemDefine!]!

    getItemsById(targets: [DataId!]!): [ItemDefine!]!

    getCategory(datasourceIds: [String!]): [CategoryDefine!]!
    getEvent(datasourceIds: [String!]): [EventDefine!]!
    getContent(id: DataId!): ContentsDetail!
    "指定のコンテンツが紐づくアイテムに関する情報を取得する"
    getBelogingItems(id: DataId!): [BelongingItemInfo!]!

    "割当候補のコンテンツを取得する"
    allocatableContents (
        "取得対象コンテンツデータソースID"
        datasourceId: String!

        "前回の続きを取得する場合に指定する"
        nextToken: String

        "指定されている場合、当該キーワードをタイトルに含むコンテンツを返す"
        keyword: String

        "trueを指定した場合、既に建物に割り当て済みのコンテンツも含めて返す"
        includeAllocated: Boolean
    ): AllocatableContentsResult!

    "指定のコンテンツのサムネイル画像を返す"
    getThumb(contentId: DataId!): String!

    "指定の画像を返す"
    getImage(imageId: Int!, size: ThumbSize!): String!

    getImageUrl(contentId: DataId!): String!

    "検索。指定の条件にヒットするアイテムやコンテンツのデータIDを返す"
    search(
        condition: Condition!
        "指定されている場合、指定のデータソースのみ検索対象にする"
        datasourceIds: [String!]
    ): [DataId!]!

    geocoder(address: String!, searchTarget: [GeocoderTarget!]!): [GeocoderItem!]!
    getGeocoderFeature(id: GeocoderIdInfo!): Geometry!

    getUserList: [User!]!
    getLinkableContentsDatasources: [ContentsDatasource!]!
}
